description: null
exclude:
- code
- node_modules
highlighter: rouge
input: GFM
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
title: Christopher Doyle
top_track:
  artist: REO Speedwagon
  name: Back on the Road Again
  playcount: 27
url: https://christopherdoyle.github.io/
