collections:
  tools:
    future: true
    output: true
description: null
exclude:
- code
- node_modules
highlighter: rouge
input: GFM
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
title: Christopher Doyle
top_track:
  artist: Pyotr Ilyich Tchaikovsky
  name: 'Tchaikovsky: 1812 Overture in E-Flat Major, Op. 49'
  playcount: 8
url: https://christopherdoyle.github.io/
